### ISSUE TITLE
Long polling doesn't work.

### ISSUE THREAD

**Issue by Nikolay-Kha** [devicehive/devicehive-java-server#109]
Steps to reproduce:
1. Start polling on device.
2. Send a command to device. Save timestamp.
3. Update command(put result) on server from device.
4. Send next poll request with saved timestamp.
5. The same command is received immediately instead of next polling iteration.

On screenshot below sample of this issue. As you can see timestamps on request and result are the same.
![pastedimage](https://cloud.githubusercontent.com/assets/8740775/10413876/4a8de7ca-6fc4-11e5-8185-0b98ef161eab.png)

**Comment by demon-xxi** [comment]
deployed to playground.devicehive.com
