### ISSUE TITLE
Authorization by device key to be deprecated.

### ISSUE THREAD

**Issue by zubrabubra** [devicehive/devicehive-java-server#116]
Instead device should use auth keys specially crafted by user and then provided for the device.
There are plenty reasons to do that, one of key point is access unification, and authentication process simplification.

**Comment by demon-xxi** [comment]
@aleksey-suprun, please take a look at WS device handler first. It does not handle AccessKey at all. You can copy functionality from WS client handler as it does respect AccessKey info.

**Comment by zubrabubra** [comment]
merged into development, closing issue
