### ISSUE TITLE
Command objects are lost under low memory

### ISSUE THREAD

**Issue by zubrabubra** [devicehive/devicehive-java-server#125]
This is applicable to the case when DH server started with a very low memory. Defect first detected when running with Xmx128M, and problem is quite simple - command update could not be fetched back by client application, server responds with 404 command not found.

Small investigation shows that Hazelcast drops out items from memory, and never persists to storage. Problem could potentially repeat even if we provide a lot memory for java application, and increase the flow of the messages.

**Comment by BoldinovaNatalya** [comment]
The map persistence feature was removed in one of the previous versions.

**Comment by demon-xxi** [comment]
Right, this is by design. The number of cached commands and notifications depends on the amount of available memory. 
@BoldinovaNatalya, please check though that server does not drop commands that are awaiting updates if they are needed for update to work. If that's the case then error should be at least written to the log.

**Comment by zubrabubra** [comment]
@demon-xxi commands awaiting updates - how can we identify those?

What if we implement some guarantee that in case server has sufficient memory it would keep command objects available for querying and updating for the 10 minutes by default, and deployer responsible to configure interval depending on the load / case.

As a part of guarantee we also share instruction how one can estimate ram required for the server to keep objects(notification/command) in memory depending on the load/parameters.
