### ISSUE TITLE
Poll implementation allows some of the messages to be missed

### ISSUE THREAD

**Issue by zubrabubra** [devicehive/devicehive-java-server#127]
This needs to be double checked, but in general flow looks like
```
1. check hazelcast
2. subscribe
2.1 check permissions
2.2 attach to kafka message consumer
```

and in case command submitted between steps 1 and 2 it would not be visible for the client who polls until he re-issue poll command.

**Comment by demon-xxi** [comment]
shouldn't we check permissions first in case they were revoked? or we have some kind of expiration time in hazelcast?

**Comment by zubrabubra** [comment]
@demon-xxi you are right accessible device list to be checked before checking whether hazelcast cache contains any messages.

**Comment by zubrabubra** [comment]
Implementation has been changed, tested with Nikolay now works better.
Closing this issue and creating one to refactor the code.
