### ISSUE TITLE
isBlocked or blocked?

### ISSUE THREAD

**Issue by henrikbjorn** [devicehive/devicehive-java-server#149]
According to the Swagger model schema for `GET /device` the proberty should be serialized as `blocked` but the java server code and the admin console expects it to be `isBlocked`.

Which is correct? https://github.com/devicehive/devicehive-java-server/blob/7487e1644ccac3f2d1d6ad0a9ac0e10a62b3cd49/src/main/java/com/devicehive/model/Device.java#L90

**Comment by demon-xxi** [comment]
@henrikbjorn thank you for pointing this out. The correct name `isBlocked`, the java annotation for swagger is not correct. I'll mark this ticket as a bug to fix that.
Please be aware that there are many other issue with swagger at this moment. We are currently working on sorting that out for next release. We may also remove redundancy in some of the methods.  

Is it possible for you to share some info on your server implementation? Perhaps we can include that to our integration tests to point out any incompatibilities earlier when we introduce change.
Also out of curiosity, do you have any benchmark numbers on it to share?

**Comment by henrikbjorn** [comment]
@demon-xxi there isnt that much to share about it. Its written in Go and designed after some of the CQRS principals, which makes it easier for us to extend in a seperate packages (if we decide to open source the implementation later on). 

Some big differences. Everything is "Eventual Consistency" which means that we pre-generate identifiers  (based on snowflake) as int64. 

Currently we cannot run the tests as they assume specific status codes, that is not correct for our usecase. Eg. we use "Accepted" instead of "Created" and so on. Also since the tests are written in JavaScript the identifiers we create will overflow (most js engines uses float to represent int64, which means the max for int in JavaScript is in53). The integer thing, is why i did the issue on using something else than JS for the tests.

**Comment by henrikbjorn** [comment]
Also i am having a REAL hard time to figure out what the changes are in the API from 1.3 to 2.0, can't seem to find a changelog.

**Comment by edubovik** [comment]
Fixed

**Comment by zubrabubra** [comment]
The problem with the name of property isBlocked/blocked has been fixed and changes were merged into the development branch; will be released soon.
