### ISSUE TITLE
Hazelcast is embedded for every instance of Devicehive 

### ISSUE THREAD

**Issue by jvovk** [devicehive/devicehive-java-server#186]
Hazelcast doesn't organize cluster as every  instance has its own name for service which gets information from zookeeper about hazelcast members. When every instance is launching, it's searching for existed members of hazelcast in zookeeper with service name applicationContext.getId() and consequently doesn't find any. This leads to strange behavior as members doesn't know about each other and can't share data. When instance is stopped, data will be lost. It's useful to have hazelcast in cluster as it can solve issues such as #160.

**Comment by sitnik** [comment]
Hazelcast has added several other methods for discovery of it's nodes in version 3. We've reworked DeviceHive java-server to not include Hazelcast server and use standalone Hazelcast instance instead.
I think this issue can be closed now.
