### ISSUE TITLE
Docker usage

### ISSUE THREAD

**Issue by dfcarpenter** [devicehive/devicehive-java-server#214]
I know 3.0.0 has a microservice architecture and I was wondering if and when the docker container / compose example will be updated with the latest version or at least if you could tell me quickly how to update the docker-compose yaml. I also was unable to run the latest docker container setup as well (DH_Version 2.0.11). Thanks!

**Comment by Nikolay-Kha** [comment]
Docker compose is already available here - https://github.com/devicehive/devicehive-docker/tree/redesign/microservices See manual here - http://docs.devicehive.com/docs/server-installation#section-building-latest-devicehive-dev-docker-images
To run latest 2.x version from docker hub use this line:
```docker run -p 80:80 devicehive/devicehive-standalone```

**Comment by sitnik** [comment]
Please consult README.md file in https://github.com/devicehive/devicehive-docker/ to run recent version of DeviceHive.
I'm closing this ticket, thank you for your question.
