### ISSUE TITLE
Invalid JSON is returned when request is not authorized

### ISSUE THREAD

**Issue by SorJEF** [devicehive/devicehive-java-server#6]
Here is a returned string, which is an invalid JSON and some clients cannot parse it:
```js
{message:"Not authorized"}
```

You can check that by simply GETting data in the browser for some endpoint which requires authorization (like GET api/device/someDeviceId).

A valid string is

```js
 {"message":"Not authorized"}
```

Furthermore Content-Type response header in this case is set to "**text/html**" and should be probably changed to "**application/json**"

**Comment by AleksandrPavlenko** [comment]
Works fine now, cannot reproduce
