### ISSUE TITLE
Non Admin users (Clients) should see only their own user

### ISSUE THREAD

**Issue by demon-xxi** [devicehive/devicehive-java-server#94]
Right now any user can query full list of users using `/user` and `/user/{id}' endpoints.
Expected for `/user` to return array of only current user.
Expected for `/user/{id}' return 401 is {id} is not for the current user.

**Comment by zubrabubra** [comment]
@demon-xxi, managed to reproduce `/user/{id}`, while `/user` is only for administrator level users.
