### ISSUE TITLE
Get rid of NullableWrapper<K> ?

### ISSUE THREAD

**Issue by demon-xxi** [devicehive/devicehive-java-server#99]
There seems to be a lot of extra code around nullable fields implementation right now. 
Can we check if that is really needed and/or is possible to replace with somethig like this: http://stackoverflow.com/questions/8748537/jax-rs-jersey-json-preserve-null-using-annotations

**Comment by zubrabubra** [comment]
There are several classes that still use this rudimentary class. Article mentioned related to JaxRs/Jersey, while we use in conjunction with gson.

**Comment by zubrabubra** [comment]
NullableWrapper is used for the purpose of handling partial updates to the entities, as it can provide backend with three different states - not present, null and value.

**Comment by zubrabubra** [comment]
@mdolbin could you please have a look and see if we can replace nullable wrapper with Option class? Semantic held by both is same.

**Comment by mdolbin** [comment]
@zubrabubra Seems like we can safely replace NullableWrapper with Optional and simplify the code around these with help of built-in methods of Optional like ```.ifPresent```, ```.map```, ```.orElse```, etc with minor code changes. WIP
